import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import JSZip from"jszip";
import{LayoutDashboard,Users,School,Activity,ClipboardCheck,BrainCircuit,Network,FileText,ShieldCheck,Plug,Upload,Download,Plus,Trash2,Pencil,Search,Moon,Sun,Save,Printer,RefreshCw,BarChart3,Target,ClipboardList,X,CheckCircle2,AlertCircle,Database,Eye,BookOpen,UserRound,Settings2,FileSpreadsheet,ArrowRight,ArrowLeft,ChevronLeft,ChevronRight,GraduationCap,Menu,LogOut}from"lucide-react";
import"./styles.css";

const DBKEY="riyadah_v4";const FILEDB="riyadah_files_v4";
const blank={school:{name:"م/م التقدم",academy:"أكاديمية فاس مكناس",directorate:"مديرية تاونات",teacher:"الأستاذ محمد الزاوي",year:"2026/2027"},groups:[],learners:[],assessments:[],support:[],tracking:[],fluency:[],lessons:[],files:[],inspector:{name:"",phone:"",email:"",notes:""},settings:{dark:false}};
const clone=x=>JSON.parse(JSON.stringify(x));
function load(){try{return {...blank,...JSON.parse(localStorage.getItem(DBKEY)||"{}")}}catch{return clone(blank)}}
function id(p){return p+"_"+crypto.randomUUID().slice(0,8)}
function size(n){return n<1024?n+" B":n<1048576?(n/1024).toFixed(1)+" KB":(n/1048576).toFixed(1)+" MB"}
function dl(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function textdl(t,n,type="text/plain"){dl(new Blob([t],{type}),n)}
function csv(rows){if(!rows.length)return"";const k=Object.keys(rows[0]),e=v=>`"${String(v??"").replaceAll('"','""')}"`;return[k.map(e).join(","),...rows.map(r=>k.map(x=>e(r[x])).join(","))].join("\n")}
function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open(FILEDB,1);r.onupgradeneeded=()=>r.result.createObjectStore("files",{keyPath:"id",autoIncrement:true});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function putFile(file){const db=await openDB();return new Promise((ok,no)=>{const t=db.transaction("files","readwrite");t.objectStore("files").add({name:file.name,type:file.type,size:file.size,blob:file});t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function allFiles(){const db=await openDB();return new Promise((ok,no)=>{const r=db.transaction("files").objectStore("files").getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function oneFile(idv){const db=await openDB();return new Promise((ok,no)=>{const r=db.transaction("files").objectStore("files").get(Number(idv));r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function delFile(idv){const db=await openDB();return new Promise((ok,no)=>{const t=db.transaction("files","readwrite");t.objectStore("files").delete(Number(idv));t.oncomplete=ok;t.onerror=()=>no(t.error)})}

function App(){
 const[d,setD]=useState(load),[page,setPage]=useState("home"),[toast,setToast]=useState(null),[search,setSearch]=useState(""),[mobile,setMobile]=useState(false);
 useEffect(()=>localStorage.setItem(DBKEY,JSON.stringify(d)),[d]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(null),2500);return()=>clearTimeout(t)}},[toast]);
 const note=(m,type="ok")=>setToast({m,type});const update=f=>setD(x=>{const n=clone(x);f(n);return n});const go=p=>{setPage(p);setMobile(false);setSearch("")};
 const nav=[["home","الرئيسية",LayoutDashboard],["learners","المتعلمون والأقسام",Users],["support","الدعم المكثف",Activity],["assessment","الرائز القبلي والبعدي",ClipboardCheck],["fluency","شبكة الطلاقة",BookOpen],["tracking","شبكات التتبع",Network],["mindmaps","خرائط الدروس",BrainCircuit],["files","مركز الملفات",FileText],["reports","التقارير",BarChart3],["inspector","المفتشة المؤطرة",ShieldCheck],["settings","الإعدادات والتكاملات",Plug]];
 const counts={learners:d.learners.length,groups:d.groups.length,support:d.support.length,assess:d.assessments.length};
 const backup=()=>{textdl(JSON.stringify(d,null,2),"riyadah-v4-backup.json","application/json");note("تم تنزيل النسخة الاحتياطية")};
 const restore=f=>{if(!f)return;const r=new FileReader;r.onload=()=>{try{setD({...blank,...JSON.parse(r.result)});note("تم الاسترجاع")}catch{note("النسخة غير صالحة","error")}};r.readAsText(f)};
 return <div className={d.settings.dark?"app dark":"app"}>
  <header><div className="brand" onClick={()=>go("home")}><div className="logo"><GraduationCap/></div><div><b>رُوّاد</b><small>منصة مؤسسات الريادة</small></div></div><div className="headerActions"><button className="icon" onClick={()=>update(x=>x.settings.dark=!x.settings.dark)}>{d.settings.dark?<Sun/>:<Moon/>}</button><button className="icon mobileMenu" onClick={()=>setMobile(!mobile)}><Menu/></button><button className="primary" onClick={()=>go("files")}><Upload/> الملفات</button></div></header>
  <div className="shell">
   <aside className={mobile?"show":""}>{nav.map(([p,l,I])=><button key={p} className={page===p?"nav active":"nav"} onClick={()=>go(p)}><I/><span>{l}</span></button>)}<div className="asideBottom"><button className="nav" onClick={backup}><Database/><span>تصدير نسخة</span></button><label className="nav"><Upload/><span>استيراد نسخة</span><input type="file" accept=".json" onChange={e=>restore(e.target.files[0])}/></label></div></aside>
   <main>{page==="home"&&<Home d={d} go={go} c={counts}/>} {page==="learners"&&<Learners d={d} update={update} note={note} search={search} setSearch={setSearch}/>} {page==="support"&&<Support d={d} update={update} note={note}/>} {page==="assessment"&&<Assessment d={d} update={update} note={note}/>} {page==="fluency"&&<Fluency d={d} update={update} note={note}/>} {page==="tracking"&&<Tracking d={d} update={update} note={note}/>} {page==="mindmaps"&&<Mindmaps d={d} update={update} note={note}/>} {page==="files"&&<Files note={note} update={update}/>} {page==="reports"&&<Reports d={d} go={go} note={note}/>} {page==="inspector"&&<Inspector d={d} update={update} note={note}/>} {page==="settings"&&<Settings d={d} update={update} note={note}/>}</main>
  </div>{toast&&<div className={"toast "+toast.type}>{toast.type==="error"?<AlertCircle/>:<CheckCircle2/>}{toast.m}</div>}
 </div>
}

const Head=({title,sub,children})=><div className="head"><div><h1>{title}</h1><p>{sub}</p></div>{children}</div>;
const Card=({title,children,actions})=><div className="card"><div className="cardHead"><h3>{title}</h3>{actions}</div>{children}</div>;
const Empty=({text,action,onClick})=><div className="empty"><FileText/><p>{text}</p>{action&&<button className="outline" onClick={onClick}><Plus/>{action}</button>}</div>;
const Stat=({I,n,t,onClick})=><button className="stat" onClick={onClick}><I/><b>{n}</b><span>{t}</span></button>;

function Home({d,go,c}){return <><Head title="لوحة القيادة" sub={`${d.school.name} • ${d.school.teacher}`}><button className="primary" onClick={()=>go("learners")}><Plus/> ابدأ التدبير</button></Head><div className="hero"><div className="heroIcon"><BrainCircuit/></div><div><span>مؤسسات الريادة</span><h2>من الرائز القبلي إلى الرائز البعدي</h2><p>منصة واحدة لتدبير القسم، الدعم المكثف، التتبع، الطلاقة، التقارير والموارد التعليمية.</p></div></div><div className="stats"><Stat I={Users} n={c.learners} t="المتعلمون" onClick={()=>go("learners")}/><Stat I={School} n={c.groups} t="الأقسام" onClick={()=>go("learners")}/><Stat I={ClipboardCheck} n={c.assess} t="نتائج الرائز" onClick={()=>go("assessment")}/><Stat I={Activity} n={c.support} t="خطط الدعم" onClick={()=>go("support")}/></div><div className="grid2"><Card title="الوصول السريع"><div className="quick"><button onClick={()=>go("learners")}><Users/> ملف متعلم</button><button onClick={()=>go("assessment")}><ClipboardCheck/> رائز</button><button onClick={()=>go("mindmaps")}><BrainCircuit/> خريطة من PPTX</button><button onClick={()=>go("reports")}><BarChart3/> تقرير</button></div></Card><Card title="الرؤية التربوية"><div className="notice"><Target/><div><b>التعلم المتمركز حول الحاجة</b><p>حدد المتعثرين من الرائز، أنشئ الدعم، تتبع المؤشرات ثم قارن النتائج البعدية.</p></div></div></Card></div></>}

function Learners({d,update,note,search,setSearch}){
 const[tab,setTab]=useState("learners"),[form,setForm]=useState({name:"",group:"",level:"السادس ابتدائي"}),[edit,setEdit]=useState(null),[profile,setProfile]=useState(null);
 const arr=(tab==="learners"?d.learners:d.groups).filter(x=>(x.name||"").includes(search));
 const add=()=>{if(!form.name.trim())return note("أدخل الاسم","error");update(x=>tab==="learners"?x.learners.push({id:id("stu"),...form,notes:""}):x.groups.push({id:id("grp"),name:form.name,level:form.level}));setForm({name:"",group:"",level:"السادس ابتدائي"});note("تمت الإضافة")};
 const remove=i=>{update(x=>{const a=tab==="learners"?x.learners:x.groups;a.splice(a.findIndex(z=>z.id===i),1)});note("تم الحذف")};
 return <><Head title="المتعلمون والأقسام" sub="ملف فردي لكل متعلم مع تتبع مستمر"/><div className="tabs"><button className={tab==="learners"?"active":""} onClick={()=>setTab("learners")}><Users/> المتعلمون</button><button className={tab==="groups"?"active":""} onClick={()=>setTab("groups")}><School/> الأقسام</button></div><Card title={tab==="learners"?"إضافة متعلم":"إضافة قسم"}><div className="formgrid"><input placeholder={tab==="learners"?"اسم المتعلم":"اسم القسم"} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>{tab==="learners"&&<input placeholder="القسم" value={form.group} onChange={e=>setForm({...form,group:e.target.value})}/>}<select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}>{["السادس ابتدائي","الخامس ابتدائي","الرابع ابتدائي","الثالث ابتدائي","الثاني ابتدائي","الأول ابتدائي"].map(x=><option key={x}>{x}</option>)}</select><button className="primary" onClick={add}><Plus/> إضافة</button></div></Card><div className="toolbar"><div className="search"><Search/><input placeholder="بحث في الأسماء..." value={search} onChange={e=>setSearch(e.target.value)}/></div><b>{arr.length}</b></div><Card title="القائمة">{arr.length?<table><thead><tr><th>الاسم</th><th>{tab==="learners"?"القسم":"المستوى"}</th><th>إجراءات</th></tr></thead><tbody>{arr.map(x=><tr key={x.id}><td><b>{x.name}</b></td><td>{tab==="learners"?x.group||"—":x.level}</td><td>{tab==="learners"&&<button className="tbl" onClick={()=>setProfile(x)}><Eye/></button>}<button className="tbl danger" onClick={()=>remove(x.id)}><Trash2/></button></td></tr>)}</tbody></table>:<Empty text="لا توجد بيانات بعد"/>}</Card>{profile&&<Profile l={profile} d={d} close={()=>setProfile(null)}/>}</>
}

function Profile({l,d,close}){const a=d.assessments.filter(x=>x.learner===l.name),s=d.support.filter(x=>x.learner===l.name),t=d.tracking.filter(x=>x.learner===l.name),f=d.fluency.filter(x=>x.learner===l.name);return <div className="overlay"><div className="modal wide"><div className="modalHead"><div><h2>{l.name}</h2><p>{l.level} • {l.group||"بدون قسم"}</p></div><button className="icon" onClick={close}><X/></button></div><div className="profileStats"><div><b>{a.length}</b><span>اختبارات</span></div><div><b>{s.length}</b><span>دعم</span></div><div><b>{t.filter(x=>x.level==="مكتسب").length}</b><span>مؤشرات مكتسبة</span></div><div><b>{f.length}</b><span>طلاقة</span></div></div><h3>نتائج الرائز</h3>{a.length?<table><tbody>{a.map(x=><tr key={x.id}><td>{x.type}</td><td>{x.subject}</td><td>{x.score}/{x.max}</td></tr>)}</tbody></table>:<p>لا توجد نتائج.</p>}</div></div>}

function Support({d,update,note}){const[f,setF]=useState({learner:"",objective:"",actions:"",status:"مفتوحة"});const add=()=>{if(!f.learner||!f.objective)return note("أكمل البيانات","error");update(x=>x.support.push({id:id("sup"),...f}));setF({learner:"",objective:"",actions:"",status:"مفتوحة"});note("تم إنشاء خطة الدعم")};return <><Head title="الدعم المكثف" sub="خطط فردية للمستفيدين والمتعثرين"/><Card title="خطة جديدة"><div className="formgrid"><select value={f.learner} onChange={e=>setF({...f,learner:e.target.value})}><option value="">المتعلم</option>{d.learners.map(x=><option key={x.id}>{x.name}</option>)}</select><input placeholder="الهدف" value={f.objective} onChange={e=>setF({...f,objective:e.target.value})}/><input placeholder="الإجراء" value={f.actions} onChange={e=>setF({...f,actions:e.target.value})}/><select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>مفتوحة</option><option>منجزة</option></select><button className="primary" onClick={add}><Plus/> إنشاء</button></div></Card><Card title="الخطط"><Rows rows={d.support} cols={["learner","objective","actions","status"]} del={i=>{update(x=>x.support=x.support.filter(z=>z.id!==i));note("تم الحذف")}}/></Card></>}

function Assessment({d,update,note}){const[f,setF]=useState({learner:"",type:"قبلي",subject:"اللغة العربية",score:"",max:"20"});const add=()=>{if(!f.learner||f.score==="")return note("أكمل البيانات","error");update(x=>x.assessments.push({id:id("ass"),...f,score:+f.score,max:+f.max}));setF({...f,score:""});note("تم تسجيل النتيجة")};const exportIt=()=>textdl(csv(d.assessments.map(x=>({المتعلم:x.learner,النوع:x.type,المادة:x.subject,النقطة:x.score,المجموع:x.max}))),"الرائز.csv","text/csv;charset=utf-8");return <><Head title="الرائز القبلي والبعدي" sub="قياس نقطة الانطلاق والأثر بعد الدعم"><button className="outline" onClick={exportIt}><Download/> تصدير CSV</button></Head><Card title="تسجيل نتيجة"><div className="formgrid"><select value={f.learner} onChange={e=>setF({...f,learner:e.target.value})}><option value="">المتعلم</option>{d.learners.map(x=><option key={x.id}>{x.name}</option>)}</select><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>قبلي</option><option>بعدي</option></select><select value={f.subject} onChange={e=>setF({...f,subject:e.target.value})}>{["اللغة العربية","الرياضيات","اللغة الفرنسية","النشاط العلمي"].map(x=><option key={x}>{x}</option>)}</select><input type="number" placeholder="النقطة" value={f.score} onChange={e=>setF({...f,score:e.target.value})}/><input type="number" value={f.max} onChange={e=>setF({...f,max:e.target.value})}/><button className="primary" onClick={add}><Plus/> تسجيل</button></div></Card><Card title="النتائج"><Rows rows={d.assessments} cols={["learner","type","subject","score","max"]} del={i=>{update(x=>x.assessments=x.assessments.filter(z=>z.id!==i));note("تم الحذف")}}/></Card></>}

function Fluency({d,update,note}){const[f,setF]=useState({learner:"",text:"",correct:"",errors:"",seconds:"60"});const add=()=>{if(!f.learner)return note("اختر متعلما","error");const correct=+f.correct||0,errors=+f.errors||0;update(x=>x.fluency.push({id:id("flu"),...f,correct,errors,wpm:Math.max(0,correct-errors)}));note("تم تسجيل شبكة الطلاقة")};return <><Head title="شبكة الطلاقة" sub="رصد السرعة والدقة والأخطاء"/><Card title="جلسة طلاقة"><div className="formgrid"><select value={f.learner} onChange={e=>setF({...f,learner:e.target.value})}><option value="">المتعلم</option>{d.learners.map(x=><option key={x.id}>{x.name}</option>)}</select><input placeholder="النص" value={f.text} onChange={e=>setF({...f,text:e.target.value})}/><input type="number" placeholder="كلمات صحيحة" value={f.correct} onChange={e=>setF({...f,correct:e.target.value})}/><input type="number" placeholder="أخطاء" value={f.errors} onChange={e=>setF({...f,errors:e.target.value})}/><button className="primary" onClick={add}><Plus/> تسجيل</button></div></Card><Card title="السجل"><Rows rows={d.fluency} cols={["learner","text","correct","errors","wpm"]} del={i=>{update(x=>x.fluency=x.fluency.filter(z=>z.id!==i));note("تم الحذف")}}/></Card></>}

function Tracking({d,update,note}){const[f,setF]=useState({learner:"",competence:"",level:"في طور الاكتساب",note:""});const add=()=>{if(!f.learner||!f.competence)return note("أكمل البيانات","error");update(x=>x.tracking.push({id:id("trk"),...f}));note("تم تحديث الشبكة")};return <><Head title="شبكات التتبع" sub="مؤشرات التعلمات ومكتسبات كل متعلم"/><Card title="إضافة مؤشر"><div className="formgrid"><select value={f.learner} onChange={e=>setF({...f,learner:e.target.value})}><option value="">المتعلم</option>{d.learners.map(x=><option key={x.id}>{x.name}</option>)}</select><input placeholder="الكفاية / المؤشر" value={f.competence} onChange={e=>setF({...f,competence:e.target.value})}/><select value={f.level} onChange={e=>setF({...f,level:e.target.value})}><option>غير مكتسب</option><option>في طور الاكتساب</option><option>مكتسب</option></select><input placeholder="ملاحظة" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/><button className="primary" onClick={add}><Plus/> إضافة</button></div></Card><Card title="الشبكة"><Rows rows={d.tracking} cols={["learner","competence","level","note"]} del={i=>{update(x=>x.tracking=x.tracking.filter(z=>z.id!==i));note("تم الحذف")}}/></Card></>}

function Mindmaps({d,update,note}){const ref=useRef(),[nodes,setNodes]=useState([]),[title,setTitle]=useState(""),[file,setFile]=useState("");async function parse(f){if(!f)return;setFile(f.name);setTitle(f.name.replace(/\.pptx$/i,""));try{const z=await JSZip.loadAsync(f),ns=Object.keys(z.files).filter(x=>/^ppt\\/slides\\/slide\\d+\\.xml$/.test(x)).sort((a,b)=>+a.match(/\\d+/)[0]-+b.match(/\\d+/)[0]),out=[];for(let i=0;i<ns.length;i++){const xml=await z.file(ns[i]).async("text"),doc=new DOMParser().parseFromString(xml,"application/xml"),t=[...doc.getElementsByTagName("*")].filter(x=>x.localName==="t").map(x=>x.textContent.trim()).filter(Boolean).join(" ");if(t)out.push({id:id("node"),title:t.split(/\\s+/).slice(0,8).join(" "),text:t})}setNodes(out);note(`تم تحليل ${out.length} شريحة`)}catch{note("تعذر قراءة الملف","error")}}const save=()=>{if(!nodes.length)return note("ارفع PPTX","error");update(x=>x.lessons.push({id:id("map"),title,nodes}));note("تم حفظ الخريطة")};const exp=()=>textdl(JSON.stringify({title,nodes},null,2),`${title||"خريطة"}.json`);return <><Head title="مختبر الخرائط الذهنية" sub="تحويل PPTX إلى خريطة منظمة محلياً"><button className="outline" onClick={exp}><Download/> تنزيل الخريطة</button></Head><Card title="استيراد الدرس"><div className="upload" onClick={()=>ref.current.click()}><Upload/><b>{file||"اختر ملف PPTX"}</b><span>يتم التحليل على جهازك دون رفع العرض إلى خادم</span><input ref={ref} type="file" accept=".pptx" onChange={e=>parse(e.target.files[0])}/></div>{nodes.length>0&&<><input className="maptitle" value={title} onChange={e=>setTitle(e.target.value)}/><div className="map"><div className="root">{title}</div>{nodes.map((n,i)=><div className="node" key={n.id}><b>{i+1}. {n.title}</b><small>{n.text}</small></div>)}</div><button className="primary" onClick={save}><Save/> حفظ الخريطة</button> <button className="outline" onClick={()=>window.print()}><Printer/> طباعة / PDF</button></>}</Card><Card title="الخرائط المحفوظة">{d.lessons.length?<div className="saved">{d.lessons.map(x=><div key={x.id}><BrainCircuit/><b>{x.title}</b><button className="tbl" onClick={()=>{setTitle(x.title);setNodes(x.nodes)}}><Eye/></button><button className="tbl danger" onClick={()=>{update(z=>z.lessons=z.lessons.filter(q=>q.id!==x.id));note("تم الحذف")}}><Trash2/></button></div>)}</div>:<Empty text="لا توجد خرائط محفوظة"/>}</Card></>}

function Files({note,update}){const input=useRef(),[fs,setFs]=useState([]);const refresh=()=>allFiles().then(setFs);useEffect(()=>{refresh()},[]);async function add(list){for(const f of list){await putFile(f);update(d=>d.files.push({id:id("file"),name:f.name,size:f.size}))}await refresh();note("تم رفع الملفات بنجاح")}async function down(i){const f=await oneFile(i);if(f)dl(f.blob,f.name)}async function remove(i){await delFile(i);await refresh();note("تم حذف الملف")}return <><Head title="مركز الملفات" sub="رفع وتنزيل وإدارة الموارد من الهاتف والكمبيوتر"><button className="primary" onClick={()=>input.current.click()}><Upload/> رفع ملفات</button></Head><input hidden ref={input} type="file" multiple onChange={e=>add(e.target.files)}/><div className="upload big" onClick={()=>input.current.click()}><Upload/><b>اسحب الملفات أو اضغط هنا</b><span>PDF • PPTX • DOCX • XLSX • صور • فيديو • أي ملف</span></div><Card title="الملفات">{fs.length?<div className="files">{fs.map(f=><div className="file"><FileText/><b>{f.name}</b><small>{size(f.size)}</small><button className="primary small" onClick={()=>down(f.id)}><Download/> تحميل</button><button className="tbl danger" onClick={()=>remove(f.id)}><Trash2/></button></div>)}</div>:<Empty text="لا توجد ملفات مرفوعة"/>}</Card></>}

function Reports({d,go,note}){const avg=d.assessments.length?d.assessments.reduce((a,x)=>a+x.score/x.max*100,0)/d.assessments.length:0;const mastered=d.tracking.filter(x=>x.level==="مكتسب").length;const csvdl=()=>textdl(csv(d.learners.map(x=>({المتعلم:x.name,القسم:x.group,المستوى:x.level}))),"المتعلمون.csv","text/csv;charset=utf-8");return <><Head title="التقارير" sub="لوحة مؤشرات قابلة للطباعة والتصدير"><button className="primary" onClick={()=>{window.print();note("اختر حفظ كـ PDF من الطابعة")}}><Printer/> PDF</button></Head><div className="stats"><Stat I={Users} n={d.learners.length} t="المتعلمون"/><Stat I={BarChart3} n={Math.round(avg)+"%"} t="متوسط الرائز"/><Stat I={Target} n={mastered} t="مكتسبات"/><Stat I={Activity} n={d.support.length} t="الدعم"/></div><Card title="مؤشرات الأداء"><div className="bars">{[["متوسط الرائز",avg],["المكتسبات",d.tracking.length?mastered/d.tracking.length*100:0],["التغطية بالدعم",d.learners.length?Math.min(100,d.support.length/d.learners.length*100):0]].map(x=><div className="bar"><span>{x[0]}</span><div><i style={{width:Math.min(100,x[1])+"%"}}/></div><b>{Math.round(x[1])}%</b></div>)}</div></Card><Card title="التصدير"><div className="quick"><button onClick={csvdl}><FileSpreadsheet/> المتعلمون CSV</button><button onClick={()=>textdl(JSON.stringify(d,null,2),"تقرير-رُوّاد.json","application/json")}><Download/> بيانات JSON</button><button onClick={()=>go("assessment")}><ClipboardList/> مراجعة الرائز</button></div></Card></>}

function Inspector({d,update,note}){const[f,setF]=useState(d.inspector),save=()=>{update(x=>x.inspector=f);note("تم حفظ البيانات")};return <><Head title="المفتشة المؤطرة" sub="بطاقة التواصل والمتابعة المهنية"/><Card title="المعلومات"><div className="stack"><input placeholder="الاسم الكامل" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="الهاتف" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="البريد الإلكتروني" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><textarea placeholder="ملاحظات الزيارة والتأطير" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/><button className="primary" onClick={save}><Save/> حفظ</button></div></Card><Card title="بيانات المؤسسة"><div className="info">{Object.entries(d.school).map(([k,v])=><div key={k}><small>{k}</small><b>{v}</b></div>)}</div></Card></>}

function Settings({d,update,note}){const[f,setF]=useState(d.school);const save=()=>{update(x=>x.school=f);note("تم حفظ إعدادات المؤسسة")};const clear=()=>{if(confirm("مسح جميع البيانات المحلية؟")){localStorage.removeItem(DBKEY);location.reload()}};return <><Head title="الإعدادات والتكاملات" sub="بيانات المؤسسة والنسخ الاحتياطي"/></Head><Card title="بيانات المؤسسة"><div className="stack"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input value={f.academy} onChange={e=>setF({...f,academy:e.target.value})}/><input value={f.directorate} onChange={e=>setF({...f,directorate:e.target.value})}/><input value={f.teacher} onChange={e=>setF({...f,teacher:e.target.value})}/><input value={f.year} onChange={e=>setF({...f,year:e.target.value})}/><button className="primary" onClick={save}><Save/> حفظ</button></div></Card><Card title="تنبيه"><div className="notice"><Database/><div><b>النسخة الحالية تعمل محلياً</b><p>البيانات تبقى في المتصفح. للحصول على مزامنة بين الهاتف والكمبيوتر وحسابات متعددة، يمكن في المرحلة التالية ربط قاعدة بيانات سحابية.</p></div></div><button className="danger" onClick={clear}><Trash2/> مسح البيانات</button></Card></>}

function Rows({rows,cols,del}){if(!rows.length)return <Empty text="لا توجد بيانات"/>;return <div className="tablewrap"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}<th>حذف</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{cols.map(c=><td key={c}>{r[c]??"—"}</td>)}<td><button className="tbl danger" onClick={()=>del(r.id)}><Trash2/></button></td></tr>)}</tbody></table></div>}

createRoot(document.getElementById("root")).render(<App/>);
